apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: shm
  namespace: kubeflow-user-example-com 
spec:
 selector:
  matchLabels:
    pipelines.kubeflow.org/v2_component: "true"
 desc: "shm volume"
 volumeMounts:
 - name: shmdir
   mountPath: /dev/shm
 volumes:
 - name: shmdir
   emptyDir:
     medium: Memory
     sizeLimit: "1G"